# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-TomKit
version:      0.01_6
version_from: lib/Apache2/TomKit.pm
installdirs:  site
requires:
    Apache::Test:                  
    APR::Request:                  
    mod_perl2:                     
    XML::LibXML:                   1.59
    XML::LibXSLT:                  1.59

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
